# Generated by Django 5.1.4 on 2024-12-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0003_alter_buses_bus_no_alter_buses_bus_sitting_capacity'),
        ('routes', '0003_remove_route_buses_remove_route_name_route_active_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('student_mobileno', models.CharField(max_length=15)),
                ('parent_mobileno', models.CharField(max_length=15)),
                ('student_address', models.TextField()),
                ('branch', models.CharField(max_length=100)),
                ('boarding_location', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('confirmation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='buses.buses')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='routes.route')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='students.student')),
            ],
        ),
    ]
